<?php

namespace AppBundle\Repository;

/**
 * GarageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MechanicRepository extends \Doctrine\ORM\EntityRepository
{

}
