<?php

namespace AppBundle\Repository;

/**
 * PartOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartOrderRepository extends \Doctrine\ORM\EntityRepository
{

}
