# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: email

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE USER]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ , roles: ROLE_USER }
        - { path: ^/orders_admin , roles: ROLE_ADMIN }
        - { path: ^/orders/updateStatus , roles: ROLE_ADMIN }

    firewalls:
        main:
            pattern:   ^/
            anonymous: true
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   logout
                target: /